name: conditional_composite

on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [main]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-22.04
    steps:
      - name: Run stage 1
        id: work_1
        uses: chipkent/test-actions/.github/actions/exitcode-action@main
        with:
          exit-code: 0
        # continue-on-error: true
      - name: Check success 1
        if: steps.work_1.outcome == 'success'
        run: |
            echo "Ran check success 1"
            exit 0
      - name: Check fail 1
        if: steps.work_1.outcome != 'success'
        run: |
            echo "Ran check fail 1"
            exit 1
    
      - name: Run stage 2
        id: work_2
        uses: chipkent/test-actions/.github/actions/exitcode-action@main
        with:
          exit-code: 1
        # continue-on-error: true
      - name: Check success 2
        if: steps.work_2.outcome == 'success'
        run: |
            echo "Ran check success 2"
            exit 1
      - name: Check fail 2
        if: steps.work_2.outcome != 'success'
        run: |
            echo "Ran check fail 2"
            exit 0
